
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const PostStatus = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed'
} as const

export type PostStatus = (typeof PostStatus)[keyof typeof PostStatus]


export const MediaType = {
  image: 'image',
  video: 'video'
} as const

export type MediaType = (typeof MediaType)[keyof typeof MediaType]
