name: Deploy to Production
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push App Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ vars.REPO }}/app:latest

      - name: Build and Push Caddy Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: config/Dockerfile
          push: true
          tags: ghcr.io/${{ vars.REPO }}/caddy:latest

      - name: Transfer Docker Compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "docker-compose.yml"
          target: "/opt/sewer-comedy"

      - name: Transfer Caddyfile
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "config/Caddyfile"
          target: "/opt/sewer-comedy"
          strip_components: 1

      - name: Deploy via Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/sewer-comedy
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            # Exportar ENVs para o docker-compose
            export GITHUB_REPOSITORY="${{ vars.REPO }}"
            export PROD_DATABASE_URL="${{ secrets.PROD_DATABASE_URL }}"
            export PROD_REDIS_URL="${{ secrets.PROD_REDIS_URL }}"
            export PROD_REDIS_PASSWD="${{ secrets.PROD_REDIS_PASSWD }}"
            export PROD_BETTER_AUTH_SECRET="${{ secrets.PROD_BETTER_AUTH_SECRET }}"
            export PROD_BETTER_AUTH_BASE_URL="${{ secrets.PROD_BETTER_AUTH_BASE_URL }}"
            export S3_ENDPOINT="${{ vars.S3_ENDPOINT }}"
            export S3_REGION="${{ vars.S3_REGION }}"
            export PROD_S3_ACCESS_KEY="${{ secrets.PROD_S3_ACCESS_KEY }}"
            export PROD_S3_SECRET_KEY="${{ secrets.PROD_S3_SECRET_KEY }}"
            export S3_BUCKET_NAME="${{ vars.S3_BUCKET_NAME }}"
            export S3_CDN_URL="${{ vars.S3_CDN_URL }}"
            export PROD_RESEND_API_KEY="${{ secrets.PROD_RESEND_API_KEY }}"

            docker compose pull
            docker compose up -d
            docker image prune -f
