name: Deploy to Production

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Generate Prisma Client
        run: bun prisma generate
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}

      - name: Build Application
        run: bun run build # Build feito com 7GB de RAM do GitHub!
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          BETTER_AUTH_BASE_URL: ${{ secrets.PROD_BETTER_AUTH_BASE_URL }}

      - name: Transfer Files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          # Enviamos a pasta build, prisma e arquivos de dependência
          source: "build,package.json,bun.lockb,prisma"
          target: "/opt/cauldrun"

      - name: Finalize Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/cauldrun
            export PATH="/home/cauldrun/.bun/bin:$PATH"

            # Instala apenas o necessário para rodar
            bun install --production

            # Migrations (Rápido, sem build pesado)
            export DATABASE_URL="${{ secrets.PROD_DATABASE_URL }}"
            bun prisma migrate deploy

            # Reinicia o servidor
            pm2 restart sveltekit-app || pm2 start build/index.js --name sveltekit-app
