name: Deploy App
on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push App Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ vars.REPO }}/app:latest

      - name: Transfer Docker Compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "docker-compose.yml"
          target: "/opt/buero"

      - name: Deploy App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /opt/buero
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            export GITHUB_REPOSITORY="${{ vars.REPO }}"
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export DB_NAME="${{ secrets.DB_NAME }}"
            export REDIS_PASSWD="${{ secrets.PROD_REDIS_PASSWD }}"
            export PROD_BETTER_AUTH_SECRET="${{ secrets.PROD_BETTER_AUTH_SECRET }}"
            export PROD_BETTER_AUTH_BASE_URL="${{ secrets.PROD_BETTER_AUTH_BASE_URL }}"
            export S3_ACCESS_KEY="${{ secrets.PROD_S3_ACCESS_KEY }}"
            export S3_SECRET_KEY="${{ secrets.PROD_S3_SECRET_KEY }}"
            export S3_BUCKET_NAME="${{ vars.S3_BUCKET_NAME }}"
            export PROD_RESEND_API_KEY="${{ secrets.PROD_RESEND_API_KEY }}"

            docker compose pull app
            docker compose up -d db redis minio varnish

            echo "Rodando migrations..."
            docker run --rm \
              --network buero_buero-network \
              --env DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}" \
              ghcr.io/${{ vars.REPO }}/app:latest \
              bun prisma migrate deploy

            docker compose up -d app
            docker image prune -f
